
name: CI-CD Workflow
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

   # JOB 1
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # JOB 2
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
           username:  ${{ secrets.DOCKER_HUB_USERNAME }}
           password:  ${{ secrets.DOCKER_HUB_TOKEN }}


     # JOB 3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
 
         
      # JOB 4
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: . # Specifies the build context (current directory)
          push: true # Set to true to push the image to Docker Hub
          tags: | # Defines the tags for the Docker image
            ${{ secrets.DOCKER_HUB_USERNAME }}/nginx-custom-server:latest # Tag with 'latest'
           
        
